spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fanfun
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: true
  redis:
    database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1000
    host: 127.0.0.1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
server:
  port: 7777